//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteDatXeCongNghe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuGiaoDich
    {
        public int MaGiaoDich { get; set; }
        public string SoDienThoai { get; set; }
        public Nullable<System.DateTime> NgayGiaoDich { get; set; }
        public string LoaiGiaoDich { get; set; }
        public decimal SoTien { get; set; }
    
        public virtual TaiXe TaiXe { get; set; }
        public virtual TaiXe TaiXe1 { get; set; }
    }
}
