//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteDatXeCongNghe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoanNganHangTaiXe
    {
        public int MaTaiKhoanNHTaiXe { get; set; }
        public string SoDienThoai { get; set; }
        public string CCCD { get; set; }
        public string SoThe { get; set; }
        public string ChuThe { get; set; }
        public Nullable<int> ThoiHanThang { get; set; }
        public Nullable<int> ThoiHanNam { get; set; }
        public Nullable<int> CVV { get; set; }
        public decimal SoDu { get; set; }
    
        public virtual TaiXe TaiXe { get; set; }
        public virtual TaiXe TaiXe1 { get; set; }
        public virtual TheVisa TheVisa { get; set; }
    }
}
