//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteDatXeCongNghe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheVisa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TheVisa()
        {
            this.TaiKhoanNganHangs = new HashSet<TaiKhoanNganHang>();
            this.TaiKhoanNganHangTaiXes = new HashSet<TaiKhoanNganHangTaiXe>();
        }
    
        public int MaThe { get; set; }
        public string SoThe { get; set; }
        public string ChuThe { get; set; }
        public Nullable<int> ThoiHanThang { get; set; }
        public Nullable<int> ThoiHanNam { get; set; }
        public Nullable<int> CVV { get; set; }
        public Nullable<decimal> SoDu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaiKhoanNganHang> TaiKhoanNganHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaiKhoanNganHangTaiXe> TaiKhoanNganHangTaiXes { get; set; }
    }
}
